services:
  - type: web
    name: dudo-dice
    runtime: node
    plan: free
    buildCommand: rm -rf node_modules frontend/node_modules server/node_modules shared/node_modules package-lock.json frontend/package-lock.json server/package-lock.json shared/package-lock.json && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
