services:
  - type: web
    name: dudo-dice
    runtime: node
    plan: free
    buildCommand: rm -f package-lock.json && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
